import { Todo } from "./todo";

export const TODOS:Todo [] = [
    {
        id: 0,
        title: "Todo1",
        content: "Content todo 1",
        author: "John Doe",
        isCompleted: false,
        createdAt: new Date(),
        completedAt: null,
    },
    {
        id: 1,
        title: "Todo2",
        content: "Content todo 2",
        author: "John Doe",
        isCompleted: false,
        createdAt: new Date(),
        completedAt: null,
    },
    {
        id: 2,
        title: "Todo3",
        content: "Content todo 3",
        author: "John Doe",
        isCompleted: false,
        createdAt: new Date(),
        completedAt: null,
    },
    {
        id: 3,
        title: "Todo4",
        content: "Content todo 4",
        author: "John Doe",
        isCompleted: false,
        createdAt: new Date(),
        completedAt: null,
    },
    {
        id: 4,
        title: "Todo5",
        content: "Content todo 5",
        author: "John Doe",
        isCompleted: false,
        createdAt: new Date(),
        completedAt: null,
    },
    {
        id: 5,
        title: "Todo6",
        content: "Content todo 6",
        author: "John Doe",
        isCompleted: false,
        createdAt: new Date(),
        completedAt: null,
    },
    {
        id: 6,
        title: "Todo7",
        content: "Content todo 7",
        author: "John Doe",
        isCompleted: false,
        createdAt: new Date(),
        completedAt: null,
    },
    {
        id: 7,
        title: "Todo8",
        content: "Content todo 8",
        author: "John Doe",
        isCompleted: false,
        createdAt: new Date(),
        completedAt: null,
    },
    {
        id: 8,
        title: "Todo9",
        content: "Content todo 9",
        author: "John Doe",
        isCompleted: false,
        createdAt: new Date(),
        completedAt: null,
    },
    {
        id: 9,
        title: "Todo10",
        content: "Content todo 10",
        author: "John Doe",
        isCompleted: false,
        createdAt: new Date(),
        completedAt: null,
    },
    
]